### ISSUE TITLE
Remote deployment

### ISSUE THREAD

**Issue by buluma** [shevabam/ezservermonitor-sh#2]
Hello
First of all kudos on this great work. Exactly what i needed.

I'm curious on how this can be used without having it sit on the physical server. More like monitor server A from server B.

Is this possible, and if yes, how can it be achieved?

Thanks again.

**Comment by shevabam** [comment]
Hello,

I don't know if I'm going to answer rightly, but you can log on to the server B via SSH from server A and run eZServerMonitor.sh

**Comment by buluma** [comment]
Hi. Yes, I've thought about that and it brings a sense of having to always
be connected to the other server or make recurrent connections to get the
data.

**Comment by shevabam** [comment]
You can run this command to refresh eSM every 60 seconds : 

    watch -t -c -n 60 ./eZServerMonitor.sh -Ca

**Comment by buluma** [comment]
Thanks. I'll give it a try and get back
