### ISSUE TITLE
/bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by cdowebcast** [shevabam/ezservermonitor-sh#7]
The line break problem.

System Message:
# ./eZServerMonitor.sh
-bash: ./eZServerMonitor.sh: /bin/bash^M: bad interpreter: No such file or directory

Solution:
`# sed -i -e 's/\r$//' eZServerMonitor.sh`

Reference:
https://raccoon.ninja/pt/dev-pt/resolvido-erro-binbashm-bad-interpreter-no-such-file-or-directory-linux/

**Comment by shevabam** [comment]
Hello,
I do not encounter the error but I have just made a modification on the file available on this repository.

**Comment by bwolfbarn** [comment]
I have also no error in files cloned from repository. However, I got the error mentionned by @cdowebcast when I loaded a few weeks ago the script from the website (not friom GitHub).
May be a check to be done if files are identical.

**Comment by shevabam** [comment]
Hi,
Ok! It's fixed ;)
Thanks
